Add flake8 linting to project
The GDS Way™[1] recommends using Flake8 to lint Python projects.

This commit takes the Flake8 config from Digital Marketplace API[2] and
removes the bits we don’t need.

It changes the `max_complexity` setting to 8, which is the most complex
code we have in this repo currently (we shouldn’t be writing code _more_
complex than what we already have).

This commit also fixes the errors found by Flake8, which includes 6(!)
tests which were never getting run because they had the same names as
existing tests.

Here is a full list of the errors that were found and fixed:
```
./notifications_utils/logging.py:3:1: F401 'os' imported but unused
./notifications_utils/logging.py:6:1: F401 'flask.current_app' imported but unused
./notifications_utils/recipients.py:10:1: F401 'flask.Markup' imported but unused
./notifications_utils/s3.py:1:1: F401 'uuid' imported but unused
./notifications_utils/timezones.py:3:1: F401 'dateutil.parser' imported but unused
./tests/test_base_template.py:4:1: F401 'flask.Markup' imported but unused
./tests/test_base_template.py:5:1: F401 'notifications_utils.template.NeededByTemplateError' imported but unused
./tests/test_base_template.py:5:1: F401 'notifications_utils.template.NoPlaceholderForDataError' imported but unused
./tests/test_base_template.py:5:1: F401 'notifications_utils.template.HTMLEmailTemplate' imported but unused
./tests/test_base_template.py:5:1: F401 'notifications_utils.template.LetterPreviewTemplate' imported but unused
./tests/test_base_template.py:182:9: F841 local variable 'template_changes' is assigned to but never used
./tests/test_logging.py:1:1: F401 'os' imported but unused
./tests/test_recipient_csv.py:4:1: F401 'flask.Markup' imported but unused
./tests/test_recipient_csv.py:7:1: F401 'notifications_utils.recipients.Columns' imported but unused
./tests/test_recipient_csv.py:8:1: F401 'notifications_utils.template.Template' imported but unused
./tests/test_recipient_csv.py:252:5: F841 local variable 'auto_generated_row_count' is assigned to but never used
./tests/test_recipient_validation.py:1:1: F401 're' imported but unused
./tests/test_recipient_validation.py:6:1: F811 redefinition of unused 'validate_phone_number' from line 6
./tests/test_recipient_validation.py:151:1: F811 redefinition of unused 'test_detect_international_phone_numbers' from line 146
./tests/test_recipient_validation.py:208:46: F841 local variable 'e' is assigned to but never used
./tests/test_recipient_validation.py:384:1: F811 redefinition of unused 'test_get_international_info' from line 156
./tests/test_redis_client.py:169:1: F811 redefinition of unused 'test_should_allow_request_if_not_over_limit' from line 163
./tests/test_redis_client.py:175:1: F811 redefinition of unused 'test_should_not_call_set_if_not_enabled' from line 75
./tests/test_template_types.py:62:9: E123 closing bracket does not match indentation of opening bracket's line
./tests/test_template_types.py:65:9: E123 closing bracket does not match indentation of opening bracket's line
./tests/test_template_types.py:68:9: E123 closing bracket does not match indentation of opening bracket's line
./tests/test_template_types.py:89:9: E123 closing bracket does not match indentation of opening bracket's line
./tests/test_template_types.py:321:1: F811 redefinition of unused 'test_sms_messages_downgrade_non_gsm' from line 311
./tests/test_template_types.py:503:47: F841 local variable 'error' is assigned to but never used
./tests/test_template_types.py:1552:9: E126 continuation line over-indented for hanging indent
./tests/test_template_types.py:1557:86: E226 missing whitespace around arithmetic operator
```

1. https://gds-way.cloudapps.digital/manuals/programming-languages/python/linting.html#how-to-use-flake8
2. https://github.com/alphagov/digitalmarketplace-api/blob/d5ab8afef4a0472f9d266d94ab4ffe1333a9aaad/.flake8